import React, { useState } from 'react';
import {
  UploadCloud,
  FileText,
  Trash2,
  AlertTriangle,
  CheckCircle,
  HelpCircle,
  TrendingUp,
  FileCheck,
  Sparkles,
  ExternalLink,
  Info
} from 'lucide-react';
import { MedicalReport, HealthBiomarker } from '../types/index.ts';

interface ReportsVaultProps {
  reports: MedicalReport[];
  onUploadReport: (payload: { fileName: string; fileData?: string; mimeType?: string; title?: string }) => Promise<void>;
  onDeleteReport: (id: string) => Promise<void>;
  onSelectBiomarkerForTrend: (paramName: string) => void;
}

export const ReportsVault: React.FC<ReportsVaultProps> = ({
  reports,
  onUploadReport,
  onDeleteReport,
  onSelectBiomarkerForTrend,
}) => {
  const [selectedReportId, setSelectedReportId] = useState<string>(reports[0]?.id || '');
  const [isUploading, setIsUploading] = useState<boolean>(false);
  const [uploadError, setUploadError] = useState<string | null>(null);

  const activeReport = reports.find((r) => r.id === selectedReportId) || reports[0];

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate size (< 10MB)
    if (file.size > 10 * 1024 * 1024) {
      setUploadError('File size exceeds 10MB limit. Please upload a smaller scan or PDF.');
      return;
    }

    setIsUploading(true);
    setUploadError(null);

    try {
      const reader = new FileReader();
      reader.onload = async () => {
        try {
          const result = reader.result as string;
          // Extract base64
          const base64Data = result.split(',')[1] || '';
          await onUploadReport({
            fileName: file.name,
            fileData: base64Data,
            mimeType: file.type || 'application/pdf',
            title: file.name.replace(/\.[^/.]+$/, '').replace(/[-_]/g, ' '),
          });
        } catch (err: any) {
          setUploadError(err.message || 'Report processing failed.');
        } finally {
          setIsUploading(false);
        }
      };
      reader.readAsDataURL(file);
    } catch (err: any) {
      setUploadError(err.message || 'Could not read file.');
      setIsUploading(false);
    }
  };

  const handleSampleUpload = async (sampleType: 'anemia' | 'metabolic') => {
    setIsUploading(true);
    setUploadError(null);
    try {
      if (sampleType === 'anemia') {
        await onUploadReport({
          fileName: 'Sample_Student_CBC_Ferritin_Panel.pdf',
          fileData: '',
          mimeType: 'application/pdf',
          title: 'Student Complete Blood Count & Iron Panel',
        });
      } else {
        await onUploadReport({
          fileName: 'Sample_Metabolic_Vitamin_Panel.pdf',
          fileData: '',
          mimeType: 'application/pdf',
          title: 'Comprehensive Youth Metabolic & Vitamin D Check',
        });
      }
    } catch (err: any) {
      setUploadError(err.message || 'Sample test upload failed.');
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <div className="space-y-6 animate-fade-in pb-12">
      {/* Preventive Health Legal & Educational Disclaimer */}
      <div className="p-4 bg-amber-50/80 rounded-2xl border border-amber-200/80 flex items-start gap-3">
        <Info className="w-5 h-5 text-amber-700 shrink-0 mt-0.5" />
        <div className="text-xs text-amber-900 leading-relaxed">
          <strong>Educational & Preventive Guidance Only:</strong> AuraHealth report interpretations are generated by GenAI to help you understand your laboratory parameters and prepare for doctor visits. This does NOT constitute medical diagnosis or treatment. Always discuss out-of-range biomarkers with your doctor or campus health physician.
        </div>
      </div>

      {/* Upload Zone & Quick Sample Drop */}
      <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-sm">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex-1">
            <h3 className="text-base font-bold text-slate-900 tracking-tight">
              Upload Medical Report (Blood Test, CBC, Vitamin, Thyroid)
            </h3>
            <p className="text-xs text-slate-500 mt-1 leading-relaxed">
              Accepts PDF, JPG, PNG from diagnostic labs (Quest, Labcorp, Hospital, Campus Clinic). Gemini 3.8 Flash extracts parameters, normal ranges, and flags trends over time.
            </p>

            {uploadError && (
              <div className="mt-3 p-2.5 bg-rose-50 text-rose-800 text-xs rounded-lg border border-rose-200">
                {uploadError}
              </div>
            )}
          </div>

          <div className="flex flex-wrap items-center gap-3">
            {/* Real File Input */}
            <label className="cursor-pointer px-4 py-2.5 text-xs font-semibold text-white bg-slate-900 hover:bg-slate-800 rounded-xl transition-all shadow-sm flex items-center gap-2">
              <UploadCloud className="w-4 h-4 text-rose-300" />
              <span>{isUploading ? 'Extracting Biomarkers...' : 'Choose File to Upload'}</span>
              <input
                type="file"
                accept=".pdf,image/png,image/jpeg"
                onChange={handleFileUpload}
                disabled={isUploading}
                className="hidden"
              />
            </label>

            {/* Quick Demo Test Buttons */}
            <button
              onClick={() => handleSampleUpload('anemia')}
              disabled={isUploading}
              className="px-3.5 py-2 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors"
            >
              + Demo CBC & Ferritin Report
            </button>
            <button
              onClick={() => handleSampleUpload('metabolic')}
              disabled={isUploading}
              className="px-3.5 py-2 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-xl transition-colors"
            >
              + Demo Vitamin & Metabolic Report
            </button>
          </div>
        </div>
      </div>

      {/* Main Reports Browser: Left Archive, Right Report Breakdown */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Report History List */}
        <div className="lg:col-span-4 space-y-3">
          <span className="text-xs font-bold uppercase tracking-wider text-slate-400 block px-1">
            Report Vault ({reports.length})
          </span>

          {reports.map((r) => {
            const isSelected = r.id === (activeReport?.id || '');
            const flaggedCount = r.parameters.filter(
              (p) => p.status === 'low' || p.status === 'high'
            ).length;

            return (
              <div
                key={r.id}
                onClick={() => setSelectedReportId(r.id)}
                className={`p-4 rounded-2xl border transition-all cursor-pointer ${
                  isSelected
                    ? 'border-slate-900 bg-slate-50/80 shadow-xs'
                    : 'border-slate-200/90 bg-white hover:border-slate-300'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-slate-500 tabular-nums">
                    {r.reportDate}
                  </span>
                  {flaggedCount > 0 ? (
                    <span className="text-[11px] font-bold text-rose-700 bg-rose-50 px-2 py-0.5 rounded-md">
                      {flaggedCount} flagged
                    </span>
                  ) : (
                    <span className="text-[11px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-md">
                      All normal
                    </span>
                  )}
                </div>

                <h4 className="text-sm font-bold text-slate-900 mt-1 leading-snug">
                  {r.title}
                </h4>

                <div className="flex items-center justify-between text-xs text-slate-400 mt-2">
                  <span className="truncate max-w-[160px]">{r.fileName}</span>
                  <span>{r.parameters.length} biomarkers</span>
                </div>
              </div>
            );
          })}
        </div>

        {/* Right: Active Report Deep Dive */}
        <div className="lg:col-span-8">
          {activeReport ? (
            <div className="bg-white rounded-2xl border border-slate-200/90 p-6 shadow-sm space-y-6">
              {/* Header */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold uppercase tracking-wider text-rose-600">
                      Report Detail
                    </span>
                    <span className="text-slate-300">·</span>
                    <span className="text-xs text-slate-500">{activeReport.reportDate}</span>
                  </div>
                  <h3 className="text-xl font-bold text-slate-900 mt-1">
                    {activeReport.title}
                  </h3>
                  <span className="text-xs text-slate-400">
                    File: {activeReport.fileName} ({(activeReport.fileSize / 1024).toFixed(0)} KB)
                  </span>
                </div>

                <button
                  onClick={() => onDeleteReport(activeReport.id)}
                  className="p-2 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-xl transition-colors self-start sm:self-auto"
                  title="Permanently delete this report and extracted parameters"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>

              {/* GenAI Plain Language Summary */}
              <div className="p-4 bg-slate-50 rounded-xl border border-slate-200/70">
                <span className="text-xs font-bold text-slate-800 uppercase tracking-wider flex items-center gap-1.5 mb-1.5">
                  <Sparkles className="w-3.5 h-3.5 text-rose-500" />
                  Plain-Language Summary
                </span>
                <p className="text-xs text-slate-700 leading-relaxed">
                  {activeReport.summary}
                </p>
              </div>

              {/* Extracted Parameters Grid */}
              <div>
                <span className="text-xs font-bold uppercase tracking-wider text-slate-400 block mb-3">
                  Extracted Biomarkers ({activeReport.parameters.length})
                </span>

                <div className="space-y-3">
                  {activeReport.parameters.map((param) => {
                    const isOptimal = param.status === 'optimal';
                    const isLow = param.status === 'low';
                    const isHigh = param.status === 'high';

                    return (
                      <div
                        key={param.id}
                        className="p-4 rounded-xl border border-slate-200/80 bg-white hover:border-slate-300 transition-all"
                      >
                        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                          <div>
                            <div className="flex items-center gap-2">
                              <h5 className="text-sm font-bold text-slate-900">
                                {param.parameterName}
                              </h5>
                              <span
                                className={`text-[11px] font-bold px-2 py-0.5 rounded-md uppercase tracking-wider ${
                                  isOptimal
                                    ? 'bg-emerald-50 text-emerald-700'
                                    : isLow
                                    ? 'bg-rose-50 text-rose-700'
                                    : 'bg-amber-50 text-amber-700'
                                }`}
                              >
                                {param.status}
                              </span>
                            </div>
                            <span className="text-xs text-slate-400 capitalize">
                              Category: {param.category.replace('_', ' ')}
                            </span>
                          </div>

                          {/* Value and normal interval */}
                          <div className="text-left sm:text-right">
                            <div className="text-lg font-bold text-slate-900 tabular-nums">
                              {param.value} <span className="text-xs font-normal text-slate-500">{param.unit}</span>
                            </div>
                            <span className="text-[11px] text-slate-400">
                              Ref: {param.referenceMin ?? 0} – {param.referenceMax ?? 'N/A'} {param.unit}
                            </span>
                          </div>
                        </div>

                        {/* Layman Explanation */}
                        <div className="mt-2.5 pt-2.5 border-t border-slate-100 text-xs text-slate-600 leading-relaxed">
                          <p><strong>What it represents:</strong> {param.plainExplanation}</p>
                          <p className="mt-1 text-slate-500"><strong>Youth Context:</strong> {param.youthRelevance}</p>
                        </div>

                        {/* Trend Button */}
                        <div className="mt-2.5 flex justify-end">
                          <button
                            onClick={() => onSelectBiomarkerForTrend(param.parameterName)}
                            className="text-xs font-medium text-slate-700 hover:text-slate-900 flex items-center gap-1"
                          >
                            <TrendingUp className="w-3.5 h-3.5 text-rose-500" />
                            <span>Plot on Longitudinal Timeline →</span>
                          </button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Questions to Discuss with Doctor */}
              {activeReport.doctorDiscussionPoints && activeReport.doctorDiscussionPoints.length > 0 && (
                <div className="p-4 bg-indigo-50/50 rounded-xl border border-indigo-100">
                  <span className="text-xs font-bold text-indigo-950 uppercase tracking-wider block mb-2">
                    Questions to Discuss with Your Healthcare Professional
                  </span>
                  <ul className="space-y-1.5 text-xs text-indigo-900">
                    {activeReport.doctorDiscussionPoints.map((q, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-indigo-400 font-bold">·</span>
                        <span>{q}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          ) : (
            <div className="bg-white rounded-2xl border border-slate-200/90 p-12 text-center text-slate-500 text-xs">
              Select or upload a report to inspect biomarkers.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
